---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accesscontrolrules.authelia.com
spec:
  group: authelia.com
  names:
    kind: AccessControlRule
    plural: accesscontrolrules
    singular: accesscontrolrule
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                domains:
                  type: array
                  items:
                    type: string
                policy:
                  type: string
                subjects:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
                networks:
                  type: array
                  items:
                    type: string
                resources:
                  type: array
                  items:
                    type: string
                methods:
                  type: array
                  items:
                    type: string
---
